server:
  port: 8764

spring:
  application:
    name: email-sender
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: dark24kot@gmail.com
    password: rweyknkioulnjswu
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            trust: "smtp.gmail.com"
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:https://eurekaserver-8cl4.onrender.com/eureka}
  instance:
    preferIpAddress: true