version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: apidb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: apidb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    env_file:
      - .dockerenv